/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FilesRouteImport } from './routes/files'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiUploadFinishRouteImport } from './routes/api/upload-finish'
import { Route as ApiUploadPrepareRouteImport } from './routes/api/upload-prepare'
import { Route as CKindRouteImport } from './routes/c.$kind'
import { Route as FSplatRouteImport } from './routes/f.$'
import { Route as VSplatRouteImport } from './routes/v.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadFinishRoute = ApiUploadFinishRouteImport.update({
  id: '/api/upload-finish',
  path: '/api/upload-finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPrepareRoute = ApiUploadPrepareRouteImport.update({
  id: '/api/upload-prepare',
  path: '/api/upload-prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const CKindRoute = CKindRouteImport.update({
  id: '/c/$kind',
  path: '/c/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const FSplatRoute = FSplatRouteImport.update({
  id: '/f/$',
  path: '/f/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VSplatRoute = VSplatRouteImport.update({
  id: '/v/$',
  path: '/v/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/repos': typeof ReposRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-finish': typeof ApiUploadFinishRoute
  '/api/upload-prepare': typeof ApiUploadPrepareRoute
  '/c/$kind': typeof CKindRoute
  '/f/$': typeof FSplatRoute
  '/v/$': typeof VSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/repos': typeof ReposRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-finish': typeof ApiUploadFinishRoute
  '/api/upload-prepare': typeof ApiUploadPrepareRoute
  '/c/$kind': typeof CKindRoute
  '/f/$': typeof FSplatRoute
  '/v/$': typeof VSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/files': typeof FilesRoute
  '/history': typeof HistoryRoute
  '/repos': typeof ReposRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-finish': typeof ApiUploadFinishRoute
  '/api/upload-prepare': typeof ApiUploadPrepareRoute
  '/c/$kind': typeof CKindRoute
  '/f/$': typeof FSplatRoute
  '/v/$': typeof VSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/files'
    | '/history'
    | '/repos'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/api/upload'
    | '/api/upload-finish'
    | '/api/upload-prepare'
    | '/c/$kind'
    | '/f/$'
    | '/v/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/files'
    | '/history'
    | '/repos'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/api/upload'
    | '/api/upload-finish'
    | '/api/upload-prepare'
    | '/c/$kind'
    | '/f/$'
    | '/v/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/files'
    | '/history'
    | '/repos'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/api/upload'
    | '/api/upload-finish'
    | '/api/upload-prepare'
    | '/c/$kind'
    | '/f/$'
    | '/v/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FilesRoute: typeof FilesRoute
  HistoryRoute: typeof HistoryRoute
  ReposRoute: typeof ReposRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUploadFinishRoute: typeof ApiUploadFinishRoute
  ApiUploadPrepareRoute: typeof ApiUploadPrepareRoute
  CKindRoute: typeof CKindRoute
  FSplatRoute: typeof FSplatRoute
  VSplatRoute: typeof VSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-finish': {
      id: '/api/upload-finish'
      path: '/api/upload-finish'
      fullPath: '/api/upload-finish'
      preLoaderRoute: typeof ApiUploadFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-prepare': {
      id: '/api/upload-prepare'
      path: '/api/upload-prepare'
      fullPath: '/api/upload-prepare'
      preLoaderRoute: typeof ApiUploadPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$kind': {
      id: '/c/$kind'
      path: '/c/$kind'
      fullPath: '/c/$kind'
      preLoaderRoute: typeof CKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$': {
      id: '/f/$'
      path: '/f/$'
      fullPath: '/f/$'
      preLoaderRoute: typeof FSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$': {
      id: '/v/$'
      path: '/v/$'
      fullPath: '/v/$'
      preLoaderRoute: typeof VSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FilesRoute: FilesRoute,
  HistoryRoute: HistoryRoute,
  ReposRoute: ReposRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUploadFinishRoute: ApiUploadFinishRoute,
  ApiUploadPrepareRoute: ApiUploadPrepareRoute,
  CKindRoute: CKindRoute,
  FSplatRoute: FSplatRoute,
  VSplatRoute: VSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
